spring:
  application:
    name: UberReviewService

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:3306/uber_local_db
    username: root
    password: Thakur@7

  jpa:
    hibernate:
      ddl-auto: validate
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true

  flyway:
    baseline-on-migrate: true